import type { FssaiRule, ProductClassification } from "./types";

/**
 * FSSAI nutraceutical / health-supplement labelling rules used by the Label
 * Compliance engine. Rule IDs are stable and shown on findings.
 *
 * Sources:
 * - FSS (Health Supplements, Nutraceuticals, FSDU, FSMP, Functional Food and
 *   Novel Food) Regulations, 2016 (as amended 2022)
 * - FSS (Labelling and Display) Regulations, 2020
 */
export const FSSAI_LABEL_RULES: FssaiRule[] = [
  {
    id: "FSSAI-NUTRA-001",
    title: "Product category declared on principal display panel",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — labelling; Labelling and Display Reg. 2020, Reg. 4",
    category: "identity",
    severity: "critical",
    appliesTo: "all",
    check: "The label must clearly state the category: Nutraceutical, Health Supplement, FSDU, FSMP, Functional Food, or Novel Food.",
    recommendation: "Print the product category (e.g. “HEALTH SUPPLEMENT”) prominently on the front panel, adjacent to the product name.",
    field: "categoryStatement",
  },
  {
    id: "FSSAI-NUTRA-002",
    title: "“NOT FOR MEDICINAL USE” declaration",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — mandatory declarations",
    category: "mandatory-declaration",
    severity: "critical",
    appliesTo: ["nutraceutical", "health-supplement", "fsdu", "functional-food", "unknown"],
    check: "The exact or equivalent declaration “NOT FOR MEDICINAL USE” must appear on the label.",
    recommendation: "Add “NOT FOR MEDICINAL USE” in capital letters on the information panel (typically back label).",
    field: "declarations.notForMedicinalUse",
  },
  {
    id: "FSSAI-NUTRA-003",
    title: "Not intended to diagnose, treat, cure or prevent any disease",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — claim restrictions / mandatory disclaimer",
    category: "mandatory-declaration",
    severity: "critical",
    appliesTo: ["nutraceutical", "health-supplement", "functional-food", "unknown"],
    check: "Label must state that the product is not intended to diagnose, treat, cure or prevent any disease.",
    recommendation: "Add: “This product is not intended to diagnose, treat, cure or prevent any disease.”",
    field: "declarations.notIntendedToDiagnoseTreatCure",
  },
  {
    id: "FSSAI-NUTRA-004",
    title: "Not to exceed the recommended daily usage",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — recommended usage declarations",
    category: "mandatory-declaration",
    severity: "high",
    appliesTo: ["nutraceutical", "health-supplement", "fsdu", "unknown"],
    check: "Label must warn not to exceed the recommended daily usage / serving.",
    recommendation: "Add: “Do not exceed the recommended daily usage.”",
    field: "declarations.notToExceedRecommendedUsage",
  },
  {
    id: "FSSAI-NUTRA-005",
    title: "Not a substitute for a varied diet",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — mandatory declarations",
    category: "mandatory-declaration",
    severity: "high",
    appliesTo: ["nutraceutical", "health-supplement", "unknown"],
    check: "Label must state the product is not a substitute for a varied diet.",
    recommendation: "Add: “This product is not to be used as a substitute for a varied diet.”",
    field: "declarations.notASubstituteForVariedDiet",
  },
  {
    id: "FSSAI-NUTRA-006",
    title: "Keep out of reach of children",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — advisory warning",
    category: "warning",
    severity: "high",
    appliesTo: ["nutraceutical", "health-supplement", "fsdu", "unknown"],
    check: "Advisory warning to keep the product out of reach of children.",
    recommendation: "Add: “KEEP OUT OF REACH OF CHILDREN.”",
    field: "declarations.keepOutOfReachOfChildren",
  },
  {
    id: "FSSAI-NUTRA-007",
    title: "Recommended usage / serving directions",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — recommended usage",
    category: "mandatory-declaration",
    severity: "critical",
    appliesTo: "all",
    check: "Clear recommended daily usage, serving size and directions for use must be stated.",
    recommendation: "State serving size (e.g. 1 capsule twice daily) and duration or “or as directed by a healthcare professional”.",
    field: "recommendedUsage",
  },
  {
    id: "FSSAI-NUTRA-008",
    title: "Target group / intended consumer",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — labelling of intended use",
    category: "identity",
    severity: "medium",
    appliesTo: ["nutraceutical", "health-supplement", "fsdu", "fsmp", "unknown"],
    check: "Label should identify the intended consumer (adults, 18+, pregnant women excluded, etc.).",
    recommendation: "Add “For adults only” or the specific target group on the information panel.",
    field: "targetGroup",
  },
  {
    id: "FSSAI-NUTRA-009",
    title: "Ingredients list with active quantities",
    regulation: "Labelling and Display Reg. 2020, Reg. 5; Health Supplements 2016 — composition",
    category: "nutrition",
    severity: "critical",
    appliesTo: "all",
    check: "Full ingredients list; nutraceuticals/health supplements must declare quantity of each active ingredient per serving.",
    recommendation: "Print ingredients in descending order of weight and a composition table (active mg/serving).",
    field: "ingredientsList",
  },
  {
    id: "FSSAI-NUTRA-010",
    title: "Nutritional information table",
    regulation: "Labelling and Display Regulations, 2020 — Nutritional information",
    category: "nutrition",
    severity: "critical",
    appliesTo: "all",
    check: "Nutritional information per 100 g/ml and per serve, with % RDA where applicable.",
    recommendation: "Add a nutrition information panel (energy, protein, carbohydrate, fat, sugars, sodium + actives) per serve and per 100 g.",
    field: "nutritionalInformation",
  },
  {
    id: "FSSAI-NUTRA-011",
    title: "Serving size declared",
    regulation: "Labelling and Display Regulations, 2020 — nutritional information",
    category: "nutrition",
    severity: "medium",
    appliesTo: "all",
    check: "Serving size must be declared (e.g. 1 capsule / 5 g / 10 ml).",
    recommendation: "Declare serving size next to the nutrition table.",
    field: "servingSize",
  },
  {
    id: "FSSAI-NUTRA-012",
    title: "% RDA for vitamins and minerals",
    regulation: "Labelling and Display Regulations, 2020 — nutritional information; Health Supplements 2016",
    category: "nutrition",
    severity: "high",
    appliesTo: ["nutraceutical", "health-supplement", "fsdu", "unknown"],
    check: "Where vitamins or minerals are declared, the label should show % RDA (or NRV) per serving.",
    recommendation: "Add % RDA per serving beside each vitamin/mineral in the nutrition / composition table.",
    field: "rdaPresent",
  },
  {
    id: "FSSAI-LAB-001",
    title: "Name of the food / product name",
    regulation: "Labelling and Display Regulations, 2020, Regulation 4",
    category: "identity",
    severity: "critical",
    appliesTo: "all",
    check: "The name of the food must appear on the principal display panel.",
    recommendation: "Place the product name prominently on the front panel.",
    field: "productName",
  },
  {
    id: "FSSAI-LAB-002",
    title: "Net quantity",
    regulation: "Labelling and Display Regulations, 2020, Regulation 6; Legal Metrology Packaged Commodities Rules",
    category: "identity",
    severity: "critical",
    appliesTo: "all",
    check: "Net quantity (count, g, ml) must be declared on the principal display panel.",
    recommendation: "Declare net quantity (e.g. “60 capsules” or “500 g”) on the front panel in the prescribed manner.",
    field: "netQuantity",
  },
  {
    id: "FSSAI-LAB-003",
    title: "Vegetarian / non-vegetarian logo",
    regulation: "Labelling and Display Regulations, 2020, Regulation 10",
    category: "identity",
    severity: "critical",
    appliesTo: "all",
    check: "Green (veg) or brown (non-veg) symbol must be present as specified.",
    recommendation: "Print the vegetarian (green filled circle in square) or non-vegetarian (brown) logo next to the product name.",
    field: "vegetarianLogo",
  },
  {
    id: "FSSAI-LAB-004",
    title: "FSSAI license number",
    regulation: "Labelling and Display Regulations, 2020, Regulation 9; FSS Act 2006",
    category: "traceability",
    severity: "critical",
    appliesTo: "all",
    check: "FSSAI license / registration number of the brand owner / manufacturer / importer / packer must be displayed.",
    recommendation: "Print “Lic. No. 1xxxxxxxxxx” (14-digit) with the FSSAI logo on the information panel.",
    field: "fssaiLicenseNumber",
  },
  {
    id: "FSSAI-LAB-005",
    title: "FSSAI logo",
    regulation: "Labelling and Display Regulations, 2020, Regulation 9",
    category: "identity",
    severity: "high",
    appliesTo: "all",
    check: "The official FSSAI logo should appear with the license number.",
    recommendation: "Place the FSSAI logo adjacent to the license number.",
    field: "fssaiLogoPresent",
  },
  {
    id: "FSSAI-LAB-006",
    title: "Name and address of manufacturer / packer / importer",
    regulation: "Labelling and Display Regulations, 2020, Regulation 7",
    category: "traceability",
    severity: "critical",
    appliesTo: "all",
    check: "Complete name and address of manufacturer, packer or importer (as applicable) must be declared.",
    recommendation: "Print manufacturer (and packer/marketer/importer if different) with full postal address.",
    field: "manufacturer",
  },
  {
    id: "FSSAI-LAB-007",
    title: "Lot / code / batch identification",
    regulation: "Labelling and Display Regulations, 2020, Regulation 8",
    category: "traceability",
    severity: "critical",
    appliesTo: "all",
    check: "A lot / code / batch number must be present for traceability.",
    recommendation: "Print Batch No. / Lot No. on the information panel or foil.",
    field: "batchLotNumber",
  },
  {
    id: "FSSAI-LAB-008",
    title: "Date of manufacture or packing",
    regulation: "Labelling and Display Regulations, 2020, Regulation 8",
    category: "traceability",
    severity: "critical",
    appliesTo: "all",
    check: "Date of manufacture or packing must be declared (month and year at minimum).",
    recommendation: "Print Mfg. Date / Packed On in DD/MM/YYYY or MM/YYYY format.",
    field: "mfgDate",
  },
  {
    id: "FSSAI-LAB-009",
    title: "Best before / Use by / Expiry date",
    regulation: "Labelling and Display Regulations, 2020, Regulation 8",
    category: "traceability",
    severity: "critical",
    appliesTo: "all",
    check: "Best before, use by, or expiry date must be declared.",
    recommendation: "Print “Best Before” or “Exp. Date” as applicable.",
    field: "expiryDate",
  },
  {
    id: "FSSAI-LAB-010",
    title: "Country of origin (imported products)",
    regulation: "Labelling and Display Regulations, 2020, Regulation 7(3)",
    category: "traceability",
    severity: "high",
    appliesTo: "all",
    check: "If the product is imported, country of origin must be declared.",
    recommendation: "For imported goods add “Country of Origin: <country>” and importer details.",
    field: "countryOfOrigin",
  },
  {
    id: "FSSAI-LAB-011",
    title: "Storage instructions",
    regulation: "Labelling and Display Regulations, 2020; Health Supplements 2016",
    category: "warning",
    severity: "medium",
    appliesTo: "all",
    check: "Storage conditions required to maintain safety/quality should be stated.",
    recommendation: "Add storage instructions (e.g. “Store in a cool, dry place away from direct sunlight”).",
    field: "storageInstructions",
  },
  {
    id: "FSSAI-LAB-012",
    title: "Allergen declaration",
    regulation: "Labelling and Display Regulations, 2020 — allergens (Schedule II)",
    category: "warning",
    severity: "high",
    appliesTo: "all",
    check: "If the product contains or may contain specified allergens, they must be declared.",
    recommendation: "Declare allergens in bold (cereals containing gluten, milk, soy, nuts, etc.) or “Contains: …”.",
    field: "allergenDeclaration",
  },
  {
    id: "FSSAI-LAB-013",
    title: "Customer care / complaints contact",
    regulation: "Labelling and Display Regulations, 2020, Regulation 7; Legal Metrology",
    category: "traceability",
    severity: "medium",
    appliesTo: "all",
    check: "Name, address, telephone or email for consumer complaints should be present.",
    recommendation: "Add a customer-care line with phone and/or email.",
    field: "customerCare",
  },
  {
    id: "FSSAI-LAB-014",
    title: "Food additive declaration",
    regulation: "Labelling and Display Regulations, 2020, Regulation 5(3)",
    category: "nutrition",
    severity: "medium",
    appliesTo: "all",
    check: "If colours, flavours or other additives are used, they must be declared with INS numbers where required.",
    recommendation: "Declare additives by class name and specific name / INS number (e.g. “Contains permitted natural colours”).",
    field: "additiveDeclaration",
  },
  {
    id: "FSSAI-CLAIM-001",
    title: "No disease / medicinal claims",
    regulation: "FSS (Health Supplements…) Regulations, 2016; Advertising and Claims Regulations, 2018",
    category: "claim",
    severity: "critical",
    appliesTo: "all",
    check: "The label must not claim to diagnose, treat, cure or prevent any disease, or use medicinal language (cure, therapy, clinical, doctor recommended unless permitted).",
    recommendation: "Remove or reword disease/medicinal claims. Structure/function wording must stay within FSSAI-permitted claims.",
  },
  {
    id: "FSSAI-CLAIM-002",
    title: "Health / structure-function claims require review",
    regulation: "FSS (Advertising and Claims) Regulations, 2018; Health Supplements 2016",
    category: "claim",
    severity: "high",
    appliesTo: "all",
    check: "Claims such as “boosts immunity”, “increases stamina”, “for heart health” need to be truthful, non-misleading, and within permitted claim lists / substantiation.",
    recommendation: "Substantiate or drop non-approved health claims. Prefer FSSAI-listed nutrient function claims with conditions of use.",
  },
  {
    id: "FSSAI-CLAIM-003",
    title: "No exaggeration of nutrient content",
    regulation: "FSS (Advertising and Claims) Regulations, 2018 — nutrient content / comparative claims",
    category: "claim",
    severity: "medium",
    appliesTo: "all",
    check: "“High in”, “rich in”, “source of” claims must meet FSSAI nutrient-content conditions.",
    recommendation: "Only use nutrient-content claims that meet the quantitative criteria; otherwise remove “rich in / high in” wording.",
  },
  {
    id: "FSSAI-FSDU-001",
    title: "FSDU category statement",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — FSDU labelling",
    category: "identity",
    severity: "critical",
    appliesTo: ["fsdu"],
    check: "Food for Special Dietary Use must be labelled as such and state the special dietary use.",
    recommendation: "Print “FOOD FOR SPECIAL DIETARY USE” and the specific dietary purpose.",
    field: "declarations.foodForSpecialDietaryUse",
  },
  {
    id: "FSSAI-FSMP-001",
    title: "FSMP — use under medical supervision",
    regulation: "FSS (Health Supplements…) Regulations, 2016 — FSMP labelling",
    category: "warning",
    severity: "critical",
    appliesTo: ["fsmp"],
    check: "FSMP labels must state that the food is to be used under medical supervision.",
    recommendation: "Add “For use under medical supervision” and the disease/condition for which it is intended (as permitted).",
  },
];

export function rulesForClassification(classification: ProductClassification): FssaiRule[] {
  return FSSAI_LABEL_RULES.filter(
    (rule) => rule.appliesTo === "all" || rule.appliesTo.includes(classification),
  );
}

export function getRuleById(id: string): FssaiRule | undefined {
  return FSSAI_LABEL_RULES.find((r) => r.id === id);
}
